In [1]:
import pandas as pd
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

from backend.scripts.data_processing import Data_Processor
from backend.scripts.wallet_size import calculate_total_wallet_size

In [2]:
my_processor = Data_Processor()

In [3]:
company_lvl_df, sens_df = my_processor.extract_external_data_from_pdfs()

17:28:45 | INFO | Pdf paths: [PosixPath('/home/chris/LagerLanguageModelsDataschool/data/downloads/AngloGold_Ashanti/annual_report__2025__annual_report.pdf')]

KeyboardInterrupt:

In [ ]:
company_lvl_df.to_csv('company_lvl_scraped_new')
sens_df.to_csv('sens_scraped_new.csv')

In [ ]:
company_lvl_df = pd.read_csv('company_lvl_scraped_new.csv')
sens_df = pd.read_csv('sens_scraped_new.csv')

In [ ]:
company_lvl_df

,Unnamed: 0,company,report_date,reporting_currency,reporting_unit,source_document,revenue,cost_of_sales,inventory,trade_receivables,trade_payables,cash_and_cash_equivalents,operating_cash_flow,total_debt,short_term_debt,long_term_debt,debt_maturity_schedule,debt_due_within_12_months,undrawn_committed_facilities,finance_costs,capital_expenditure,currencies_exposed_to,employee_expenses,employee_count,dividends_paid,tax_paid,countries_of_operation,foreign_subsidiaries,major_customers_suppliers,commodity_exposure,interest_rate_exposure,bond_issues,bond_maturity_dates,credit_facilities_and_lenders,major_contractual_commitments,order_book_project_pipeline,share_price,share_return,ownership_major_shareholders,extra_notes,foreign_revenue,revenue_by_geography,exports_exposure,security_collateral_on_debt,credit_rating,fx_hedging_policy,contingent_liabilities,commodity_derivatives,interest_rate_derivatives,debt_due_12_to_24_months,fx_derivative_notional,guarantees_outstanding,receivable_days,payable_days,inventory_days,imports_exposure,market_capitalisation,assets_under_management,foreign_currency_assets,foreign_currency_liabilities
0,0,Anglo American,2026-06-30,USD,billions,Our 2026 Half Year Results,18546.000,17194.0,3819.0,2390.0,2479.0,6436.000,7005.0,8.2,1075.0,14406.0,"Medium and long-term borrowings of $14,406 mil...",1075.0,5951.0,492.0,3322.0,['USD'],3322.0,43000,344.000,1329.0,"['AU', 'BR', 'BW', 'CA', 'CL', 'CO', 'DE', 'EC...","['Anglo American Quellaveco S.A.', 'Anglo Amer...","['China customers', 'Enel X', 'Mitsubishi Corp...","['copper', 'crop nutrients', 'iron ore', 'mang...",Principally exposed to US and South African in...,EUR 745 million sustainability-linked notes du...,"['2026-03', '2027-04', '2027-05', '2027-09', '...",Bilateral and syndicated borrowing facilities ...,Capital commitments relating to acquisition of...,Joint mine plan agreed with Codelco to unlock ...,NaN,NaN,"['BlackRock Inc.', 'Epoch Two Investment Holdi...",Anglo American is progressing a portfolio tran...,NaN,"China $9,612m, Other Asia $3,239m, Other Afric...","Global sales across Asia, Europe, South Americ...",NaN,NaN,"Generally not to hedge South African rand, Aus...",291.0,"Interest rate swaps, cross-currency interest r...",Interest rate swaps used to convert fixed rate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,AngloGold Ashanti,2026-06-30,USD,millions,Q2 2026 Earnings Results,3104.000,1528.0,1285.0,122.0,558.0,2769.000,1214.0,1778.0,12.0,1559.0,"Total borrowings of $2,044 million. $19 millio...",12.0,1465.0,38.0,549.0,['USD'],880.0,41416,827.000,542.0,"['AR', 'AU', 'BR', 'CD', 'CO', 'EG', 'GH', 'GN...","['AngloGold Ashanti (Ghana) Limited', 'AngloGo...","['ANZ Investment Bank Ltd', 'JP Morgan Chase N...",['gold'],Exposed to variable interest rates on borrowin...,Repurchased approximately $666m principal amou...,"['2028-11-01', '2030-10-01', '2040-04-15']",Undrawn $1.4bn multi-currency revolving credit...,Contracted capital expenditure of $378 million...,Advanced exploration and development projects ...,85.28,2.75,"['BlackRock, Inc.', 'Public Investment Corpora...",Q2 2026 earnings results presentation; targeti...,9893.0,"Africa: $7,152m, Australia: $1,876m, Americas:...",Refined gold and doré bars sold directly to bu...,"Unsecured borrowings and credit facilities, wi...",BB+ / Baa3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Aspen Pharmacare,2025-12-31,ZAR,millions,Interim Results Presentation H1 2026,21085.000,11501.0,16919.0,11166.0,4084.0,6642.000,3577.0,28567.0,4612.0,31508.0,"Less than 1 year: R4,612 million; Between 1-2 ...",4612.0,15900.0,725.0,1580.0,"['AUD', 'BRL', 'CNY', 'EUR', 'MXN', 'USD', 'ZAR']",10874.0,9557,941.000,264.0,"['CN', 'ZA']","['A.Pharma Distribuidora Limitada', 'Alphamed ...",NaN,NaN,Exposed to floating and fixed interest rates a...,NaN,NaN,Euro syndicated term and revolving loans (Faci...,Authorised and contracted capital commitments ...,NaN,NaN,NaN,"['Allan Gray', 'Attridge, MG', 'Bank of New Yo...",Interim results for the period ended 31 Decemb...,NaN,"Africa Middle East: R10,086 million; Americas:...",NaN,Inventories to the value of R3.5 billion have ...,BB or better international credit rating,Through the selective use of forward exchange ...,279.0,NaN,NaN,3741.0,5022.0,73175.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,BHP Group,2025-12-31,USD,billions,Financial results for the half year ended 31 D...,27.902,NaN,5817.0,5452.0,6288.0,13466.000,9372.0,28021.0,3431.0,24590.0,"Bank loans, debentures and other loans undisco...",3431.0,5500.0,705.0,5.3,"['AUD', 'BRL', 'CAD', 'CLP', 'USD', 'ZAR']",5017.0,41463,3080.000,3662.0,"['AR', 'AU', 'BR', 'CA', 'CL', 'PE', 'US']","['BHP Billiton Brasil Ltda', 'Vicuña Corp.']","['Caterpillar', 'Komatsu', 'Lundin Mining', 'R...","['copper', 'energy coal', 'gold', 'iron ore', ...",98 per cent of borrowings exposed to floating ...,USD bonds issued by BHP Billiton Finance (USA)...,"['2030-12-31', '2032-12-31', '2035-12-31']",US$850 million 5-year unsecured syndicated ter...,Obligations under the Brazil Agreement (Obliga...,"Growth pipeline includes Jansen Stage 1 & 2, V...",NaN,NaN,"['BlackRock Group', 'Citigroup Global Markets ...",BHP announced a silver streaming agreement wit...,48717.0,"Australia: US$2,545M; Europe: US$1,121M; China...",NaN,"All interest bearing liabilities, excluding le...",Moody's A1 (stable) / P-1; Fitch A (stable) / F1,BHP Brasil's expected payments up to FY28 for ...,2575.0,NaN,Interest rate swaps and cross currency interes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Bid Corporation,2025-12-31,ZAR,millions,Investor presentation For the half year ended ...,126288.900,177918144.0,18247.1,23608.5,29250696.0,9022.300,8800.0,16795.0,2953.8,13841.2,"Within 1 year: R3,501,563 thousand; 1 year to ...",2953.8,26400000.0,583.3,2700.0,"['GBP', 'ZAR']",28200.0,30581,2000.000,1600.0,"['AE', 'AR', 'AU', 'BH', 'BR', 'CH', 'CL', 'CN...","['Blancaluna Group', 'Broekhuyzen Horecaservic...",['Subway'],NaN,Mixture of fixed (95% fixed long-term funding)...,NaN,NaN,"A €75 million bilateral bank loan, which matur...",Capital expenditure approved and contracted fo...,NaN,NaN,NaN,"['BlackRock Advisors LLC', 'Coronation Asset M...",Group has R20.6 billion of available headroom ...,226164223.0,"Australasia: R23,3 bn, United Kingdom: R36,4 b...",NaN,"Property, plant and equipment with an estimate...",NaN,Liabilities matched to underlying assets for a...,NaN,NaN,NaN,5413352.0,NaN,NaN,36.0,62.0,36.0,NaN,NaN,NaN,NaN,NaN
5,5,Clicks Group,2026-02-28,ZAR,millions,Interim group results for the six months ended...,24872.000,19047733.0,9034.0,4100643.0,11920656.0,1238.000,1900.0,4414007.0,1334.0,2708.0,NaN,1334.0,2600.0,207355.0,311.0,['ZAR'],2732.0,20682,1515.000,651.0,"['BW', 'ZA']","['Botswana', 'Eswatini', 'Lesotho', 'Namibia']","['Clicks', 'Independent pharmacies', 'Private ...",NaN,NaN,NaN,NaN,South African financial institutions provide f...,Capital commitments contracted for but not yet...,NaN,31821.00,NaN,"['BlackRock (US and UK)', 'GIC Asset Managemen...",Diluted HEPS up 8.1% to 652.8 cps; interim div...,NaN,NaN,NaN,NaN,NaN,The group continues to hedge direct exposures ...,NaN,NaN,NaN,NaN,NaN,NaN,38.0,84.0,89.0,With 8.2% of products sourced through direct i...,74413727.0,NaN,NaN,NaN
6,6,Glencore,2026-06-30,USD,billions,2026 Half-Year Results,174430.000,167798.0,38178.0,2355.0,5525.0,3626.000,8.1,42.4,18072.0,27184.0,Bond maturities maintained around a cap of no ...,18072.0,14.0,1681.0,4.0,"['AUD', 'CAD', 'CLP', 'COP', 'KZT', 'PEN', 'US...",7110.0,140000,995.000,633.0,"['AR', 'AU', 'CA', 'CD', 'CH', 'GB', 'PE']","['Altyntau Kokshetau JSC', 'ARM Coal (Propriet...",NaN,"['coal', 'cobalt', 'copper', 'gold', 'lead', '...",Exposed to floating rate debt based primarily ...,"5-year $650 million, 4.900% coupon bond; 7-yea...","['2026-03-26', '2026-04', '2026-10', '2027-03'...","$10,635 million one-year revolving credit faci...",Contractually committed capital expenditure of...,Progressing copper projects including El Pachó...,NaN,NaN,"['BlackRock, Inc.', 'Ivan Glasenberg', 'Qatar ...",Glencore is applying to establish a secondary ...,NaN,"The Americas: $39,193 million, Europe: $66,843...",NaN,Inventories pledged under dedicated financing ...,"A3, BBB+",Uses cross-currency swaps and forward exchange...,NaN,"Uses futures, options, swaps, and physical for...",Interest rate swaps used as fair value hedges ...,NaN,NaN,587.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN
7,7,Gold Fields,2025-12-31,USD,millions,Gold Fields FY 2025 Results Presentation,8751.300,3680.8,1156.0,380.7,225.0,1779.200,4534.0,1400.0,178.7,2559.5,Borrowings comprise current portion of borrowi...,178.7,1300.7,120.7,1399.0,['USD'],607.0,6628,761.900,789.7,"['AU', 'CA', 'CL', 'GH', 'PE', 'ZA']","['Abosso Goldfields Limited', 'Gold Fields Gha...",['Engineers and Planners (E&P)'],"['copper', 'gold']",Borrowings include variable-rate obligations (...,US$500m 10-year notes maturing in May 2029; US...,"['2029-05-31', '2032-05-31']",US$1.2bn sustainability-linked syndicated revo...,Total capital expenditure is expected to range...,"Windfall project in Canada, Salares Norte expa...",44.05,NaN,['Public Investment Corporation (Government Em...,FY 2025 results presentation highlighting 2.44...,8751.3,"Revenue generated from South Africa, Ghana, Pe...",NaN,NaN,"Moody's: Baa3, stable outlook; S&P: BBB-, stab...","Given the volatility of the gold price, Gold F...",NaN,NaN,NaN,NaN,NaN,230.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,MTN Group,2025-12-31,ZAR,millions,Mobile Telephone Networks Holdings Limited Ann...,227354.000,NaN,1310.0,18566.0,21475.0,41909.000,77519.0,70455.0,17755.0,52700.0,Borrowings mature across various dates ranging...,17755.0,35948.0,19890.0,50826.0,"['BWP', 'CAD', 'CHF', 'CNY', 'EUR', 'GBP', 'GH...",14736.0,14970,6800.000,12053.0,"['AF', 'BJ', 'BW', 'CD', 'CF', 'CG', 'CI', 'CM...","['Bayobab', 'MTN Cameroon', 'MTN Congo-Brazzav...",NaN,NaN,Exposed to floating and fixed interest rates a...,"USD senior unsecured notes, listed and unliste...",['2026-06-30'],Various committed and uncommitted debt facilit...,"Property, plant and equipment capital commitme...",NaN,NaN,NaN,['MTN Group Limited'],The Group operates in multiple hyperinflationa...,NaN,"South Africa: R51 090m, Nigeria: R61 694m, SEA...",NaN,Certain borrowings are secured by floating cha...,NaN,"Natural hedges are considered, and derivative ...",1812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310000.0,NaN,NaN,NaN
9,9,NEPI Rockcastle,2025-12-31,EUR,millions,NEPI Rockcastle February 2026 Presentation,930663.000,NaN,0.0,97294.0,179289.0,314.000,572583.0,3014680.0,501179.0,3443420.0,"Repayment profile: <1 year: €300,991 thousand;...",300991.0,740.0,103963.0,206383.0,['EUR'],14225.0,680,391139.000,33698.0,"['BG', 'CZ', 'HR', 'HU', 'LT', 'PL', 'RO', 'SK']","['NE Property B.V.', 'Nepiom Limited']","['Auchan', 'Carrefour', 'CCC', 'H&M', 'LPP', '...",NaN,16% of total outstanding debt is unhedged (mai...,€500m 8-year maturity Green bond issued at 3.8...,"['2026-10-09', '2027-07-14', '2030-01-21', '20...","RCF capacity of €740m (fully undrawn, extended...",Pipeline of developments and energy projects u...,€845m total investments under permitting & con...,NaN,15.00,"['Coronation Fund Managers', 'Fortress Real Es...",Leading commercial real estate company in CEE ...,NaN,NaN,NaN,"General security over properties, current asse...",BBB/+,NaN,NaN,NaN,Interest rate caps and fixed interest rate swa...,506540.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,Naspers,2026-03-31,USD,billions,Prosus FY26 Results Presentation,10848.000,6027.0,347.0,608.0,1170.0,6820.000,1627.0,17975.0,1987.0,15988.0,"Total long-term liabilities of US$15,988m and ...",1987.0,NaN,685.0,219.0,['USD'],2686.0,45780,528.000,252.0,"['BR', 'CN', 'IN', 'ZA']","['Despegar', 'iFood', 'Just Eat Takeaway.com',...",NaN,NaN,NaN,Group's euro-denominated bonds and additional ...,NaN,NaN,NaN,NaN,NaN,NaN,"['Keeromstraat 30 Beleggings (RF) Limited', 'N...",Naspers holds 43% of Prosus and repurchased $1...,NaN,NaN,NaN,NaN,Investment-grade rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,OUTsurance Group,2025-12-31,ZAR,millions,"RESULTS ANNOUNCEMENT, CASH ORDINARY AND SPECIA...",20485.000,NaN,NaN,NaN,NaN,1865.000,6195.0,0.0,NaN,NaN,NaN,NaN,1350.0,90.0,373.0,"['AUD', 'ZAR']",6771.0,8100,3714.000,2315.0,"['AU', 'IE', 'ZA']","['OUTsurance Holdings Limited', 'OUTsurance Ir...",NaN,NaN,Exposed to interest rate risk through interest...,NaN,NaN,"Access to a revolving credit facility of R1,35...",Committed capital to fund growth in OUTsurance...,NaN,78.85,NaN,"['Public Investment Corporation', 'Remgro Limi...",Multinational insurance group servicing 3.7 mi...,NaN,NaN,NaN,NaN,NaN,Utilises derivative financial instruments such...,NaN,NaN,Interest rate swaps used to manage interest ra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121195.0,NaN,NaN,NaN
12,12,Pepkor Holdings,2025-09-30,ZAR,millions,Pepkor Holdings Limited Annual Financial State...,95340.000,57388.0,18618.0,1551.0,12023.0,5066.000,4466.0,13383.0,1200.0,12183.0,"Repayable next year: R1,200 million; within tw...",1200.0,NaN,3354.0,2404.0,"['BRL', 'CNY', 'EUR', 'GBP', 'USD', 'ZAR']",10689.0,48500,1787.000,1860.0,"['AO', 'BR', 'BW', 'LS', 'MW', 'MZ', 'NA', 'SZ...","['Pepco Poland Sp. z.o.o', 'Pepkor Europe GmbH...",NaN,NaN,"Borrowings bear interest at variable, market-d...",Domestic Medium Term Note Programme,"['2026-03-06', '2026-05-05', '2027-03-06', '20...",Revolving credit facilities with lenders inclu...,Contracts for capital expenditure amounting to...,NaN,2431.00,NaN,"['Alexander Forbes Investments', 'Government o...",Ainsley Holdings Proprietary Limited and SAHPL...,13884.0,"South Africa: R81,456 million, Other foreign c...",NaN,Long- and short-term investments at banking in...,NaN,Hedge between 60% and 80% of forecast US dolla...,NaN,NaN,NaN,1190.0,NaN,NaN,NaN,NaN,NaN,NaN,89.8,NaN,NaN,NaN
13,13,Prosus,2026-03-31,USD,millions,Annual Report 2026,9705.000,5198.0,271.0,570.0,1109.0,6682.000,1609.0,17465.0,1950.0,15515.0,Repayment terms of long-term liabilities: Paya...,1903.0,2500.0,645.0,5891.0,"['BRL', 'CAD', 'EUR', 'GBP', 'INR', 'PLN', 'RO...",2456.0,41998,508.000,252.0,"['AR', 'AT', 'AU', 'BR', 'CA', 'CH', 'CL', 'CO...","['Dante International S.A. (eMAG)', 'Despegar....",NaN,NaN,Exposed to overnight risk-free average rates (...,Publicly traded bonds listed on the Irish Stoc...,"['2026-07-01', '2027-01-01', '2027-07-01', '20...",Undrawn multi-currency revolving credit facili...,Other service commitments of US$550m and lease...,NaN,NaN,NaN,['Naspers Limited'],Prosus has transformed from a financial holdin...,NaN,"Asia: US$808m, Europe: US$5,768m, LatAm: US$2,...",NaN,"Property, plant and equipment, investments, ca...",Baa2 (Moody's) / BBB (Standard and Poor's),NaN,NaN,NaN,NaN,882.0,NaN,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,Sanlam,2025-12-31,ZAR,millions,Sanlam Limited Annual Financial Statements 2025,25749.000,1507.0,NaN,18629.0,36891.0,36179.000,2428.0,18578.0,3237.0,15331.0,"Due within one year: R6,386 million; Due withi...",6386.0,3850.0,1809.0,484.0,"['BWP', 'EGP', 'EUR', 'GBP', 'INR', 'MAD', 'MY...",19667.0,23363,11171.000,8085.0,"['CI', 'GH', 'KE', 'MY', 'NA', 'ZA']","['MCIS Insurance', 'Pacific & Orient Insurance...",NaN,NaN,Exposed to fixed-rate and floating-rate intere...,Unsecured subordinated bonds and commercial pa...,"['2026-08-16', '2028-04-06', '2028-08-16', '20...",Standard Bank bridge loan facility of R6.5 bil...,Future lease commitments amounting to R165 mil...,NaN,NaN,NaN,"['Government Employees Pension Fund (PIC)', 'U...",Sanlam announced various subsequent strategic ...,NaN,"South Africa: R23,618 million; Pan-Africa: R25...",NaN,"Repurchase agreement positions of R17,961 mill...",South Africa National Scale: zaA+ for Sanlam L...,Foreign currency mismatch risk is mitigated by...,NaN,NaN,"Interest rate swaps, caps, floors and other de...",1590.0,NaN,128.0,NaN,NaN,NaN,NaN,NaN,1348527.0,NaN,NaN
15,15,Shaftesbury Capital plc,2025-12-31,GBP,millions,2025 Annual Report,238.900,28.4,NaN,18.2,NaN,361.400,116.4,1210.8,438.4,772.4,Debt matures between March 2026 and 2037. 2026...,438.4,675.0,63.8,114.6,['GBP'],28.4,101,72.200,NaN,['GB'],NaN,"['CBRE', 'Cushman & Wakefield', 'Veolia']",NaN,Majority of debt is at fixed rates or has inte...,£275 million of secured exchangeable bonds mat...,['2026-03-31'],Three revolving credit facilities totalling £7...,Contractually committed to £10.8 million of fu...,NaN,1.45,26.10,"['BlackRock, Inc.', 'Government of South Afric...",Shaftesbury Capital is a central London mixed-...,NaN,All revenue has been generated from operations...,NaN,£517.4 million of borrowings are secured by fi...,NaN,NaN,NaN,NaN,Interest rate caps protecting against SONIA ex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5184.5,NaN,NaN
16,16,Shoprite Holdings,2025-12-28,ZAR,millions,2026 Interim Results Presentation,136796.000,104179.0,33700.0,3506.0,24474.0,15100.000,10984.0,6993.0,489.0,6504.0,Borrowings consist of short-term and long-term...,489.0,11600.0,2525.0,3931.0,['ZAR'],10801.0,168939,2700.000,3366.0,"['BW', 'GH', 'LS', 'MW', 'MZ', 'NA', 'SZ', 'ZA...","['Africa Supermarkets Ltd', 'Checkers (Chatswo...",NaN,NaN,Borrowings and call accounts carry floating in...,NaN,NaN,Unutilised banking facilities of R11.6 billion...,"Contracted for property, plant and equipment a...",NaN,NaN,NaN,"['BlackRock', 'Capital Group', 'CH Wiese', 'Co...",Group plans to add 123 new stores within core ...,23044.0,"South Africa: R229,657 million (external sale ...",NaN,Borrowings and credit facilities are unsecured.,NaN,The Group uses call deposits in foreign curren...,2125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,The Bidvest Group,2025-12-31,ZAR,billions,Bidvest Investor Presentation For the half yea...,66.700,48003864.0,14757949.0,19181937.0,18297790.0,4974493.000,8.7,38398914.0,9494854.0,28904060.0,Maturity well spread and extended to FY33 with...,9494854.0,28917388.0,1532464.0,1.4,"['CAD', 'EUR', 'GBP', 'USD', 'ZAR']",40801516.0,130000,1.700,0.9,"['GB', 'MU', 'NA', 'SG', 'ZA']","['Citron Hygiene Holdings Inc.', 'Countrywide ...","['Eskom', 'Natco Pharma', 'Pizza Express', 'St...","['Chrome', 'Coal', 'Gold', 'Manganese']",Retained overweight variable rate exposure at ...,"Bidvest Group UK 6.2% Sep 2032, Bidvest Group ...","['2026-09-30', '2032-09-30']",Available funding EUR 442 million + R12 billio...,R95.4 million investment in warehousing/facili...,"Strong forward order books reported in travel,...",NaN,NaN,"['GIC Asset Management Pte Ltd', 'Government E...",Disposal processes: Bidvest Bank transaction t...,18414060.0,"Southern Africa: R48,158,337 thousand; Interna...","Exports of agricultural bulk volumes (maize, s...","Certain property, plant and equipment and inve...",NaN,"Fixed-for-fixed, USD/GBP pair cross currency s...",NaN,NaN,NaN,4451312.0,NaN,NaN,NaN,NaN,NaN,"Import volumes of wheat, rice, and bulk commod...",NaN,NaN,NaN,NaN

In [ ]:
standard_ext_data, standard_sens_data = my_processor.standardize_data(company_lvl_df, sens_df)

In [ ]:
standard_ext_data

,Unnamed: 0,company,report_date,reporting_currency,reporting_unit,source_document,revenue,cost_of_sales,inventory,trade_receivables,trade_payables,cash_and_cash_equivalents,operating_cash_flow,total_debt,short_term_debt,long_term_debt,debt_maturity_schedule,debt_due_within_12_months,undrawn_committed_facilities,finance_costs,capital_expenditure,currencies_exposed_to,employee_expenses,employee_count,dividends_paid,tax_paid,countries_of_operation,foreign_subsidiaries,major_customers_suppliers,commodity_exposure,interest_rate_exposure,bond_issues,bond_maturity_dates,credit_facilities_and_lenders,major_contractual_commitments,order_book_project_pipeline,share_price,share_return,ownership_major_shareholders,extra_notes,foreign_revenue,revenue_by_geography,exports_exposure,security_collateral_on_debt,credit_rating,fx_hedging_policy,contingent_liabilities,commodity_derivatives,interest_rate_derivatives,debt_due_12_to_24_months,fx_derivative_notional,guarantees_outstanding,receivable_days,payable_days,inventory_days,imports_exposure,market_capitalisation,assets_under_management,foreign_currency_assets,foreign_currency_liabilities,original_currency,fx_rate_to_zar,fx_rate_date
0,0,Anglo American,2026-06-30,ZAR,units,Our 2026 Half Year Results,3.045129e+14,2.823140e+14,6.270542e+13,3.924220e+13,4.070352e+13,1.056748e+14,1.150174e+14,1.346385e+11,1.765078e+13,2.365369e+14,"Medium and long-term borrowings of $14,406 mil...",1.765078e+13,9.771144e+13,8.078311e+12,5.454502e+13,[USD],5.454502e+13,43000.0,5.648250e+12,2.182129e+13,"[AU, BR, BW, CA, CL, CO, DE, EC, FI, GB, NA, P...","['Anglo American Quellaveco S.A.', 'Anglo Amer...","['China customers', 'Enel X', 'Mitsubishi Corp...","['copper', 'crop nutrients', 'iron ore', 'mang...",Principally exposed to US and South African in...,EUR 745 million sustainability-linked notes du...,"['2026-03', '2027-04', '2027-05', '2027-09', '...",Bilateral and syndicated borrowing facilities ...,Capital commitments relating to acquisition of...,Joint mine plan agreed with Codelco to unlock ...,NaN,NaN,"['BlackRock Inc.', 'Epoch Two Investment Holdi...",Anglo American is progressing a portfolio tran...,NaN,"China $9,612m, Other Asia $3,239m, Other Afric...","Global sales across Asia, Europe, South Americ...",NaN,NaN,"Generally not to hedge South African rand, Aus...",4.778025e+12,"Interest rate swaps, cross-currency interest r...",Interest rate swaps used to convert fixed rate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.419331,2026-06-29
1,1,AngloGold Ashanti,2026-06-30,ZAR,units,Q2 2026 Earnings Results,5.096560e+10,2.508874e+10,2.109884e+10,2.003158e+09,9.161986e+09,4.546513e+10,1.993307e+10,2.919357e+10,1.970320e+08,2.559774e+10,"Total borrowings of $2,044 million. $19 millio...",1.970320e+08,2.405432e+10,6.239346e+08,9.014212e+09,[USD],1.444901e+10,41416.0,1.357879e+10,8.899277e+09,"[AR, AU, BR, CD, CO, EG, GH, GN, TZ, US]","['AngloGold Ashanti (Ghana) Limited', 'AngloGo...","['ANZ Investment Bank Ltd', 'JP Morgan Chase N...",['gold'],Exposed to variable interest rates on borrowin...,Repurchased approximately $666m principal amou...,"['2028-11-01', '2030-10-01', '2040-04-15']",Undrawn $1.4bn multi-currency revolving credit...,Contracted capital expenditure of $378 million...,Advanced exploration and development projects ...,1400.240513,2.75,"['BlackRock, Inc.', 'Public Investment Corpora...",Q2 2026 earnings results presentation; targeti...,1.624364e+11,"Africa: $7,152m, Australia: $1,876m, Americas:...",Refined gold and doré bars sold directly to bu...,"Unsecured borrowings and credit facilities, wi...",BB+ / Baa3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.419331,2026-06-29
2,2,Aspen Pharmacare,2025-12-31,ZAR,units,Interim Results Presentation H1 2026,2.108500e+10,1.150100e+10,1.691900e+10,1.116600e+10,4.084000e+09,6.642000e+09,3.577000e+09,2.856700e+10,4.612000e+09,3.150800e+10,"Less than 1 year: R4,612 million; Between 1-2 ...",4.612000e+09,1.590000e+10,7.250000e+08,1.580000e+09,"[AUD, BRL, CNY, EUR, MXN, USD, ZAR]",1.087400e+10,9557.0,9.410000e+08,2.640000e+08,"[CN, ZA]","['A.Pharma Distribuidora Limitada', 'Alphamed ...",NaN,NaN,Exposed to floating and fixed interest rates a...,NaN,NaN,Euro syndicated term and revolving loans (Faci...,Authorised and contracted capital commitments ...,NaN,NaN,NaN,"['Allan Gray', 'Attridge, MG', 'Bank of New Yo...",Interim results for the period ended 31 Decemb...,NaN,"Africa Middle East: R10,086 million; Americas:...",NaN,Inventories to the value of R3.5 billion have ...,BB or better international credit rating,Through the selective use of forward exchange ...,2.790000e+08,NaN,NaN,3.741000e+09,5.022000e+09,7.317500e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-31
3,3,BHP Group,2025-12-31,ZAR,units,Financial results for the half year ended 31 D...,4.627678e+11,NaN,9.647768e+13,9.042398e+13,1.042894e+14,2.233399e+14,1.554390e+14,4.647415e+14,5.690475e+13,4.078367e+14,"Bank loans, debentures and other loans undisco...",5.690475e+13,9.122009e+13,1.169276e+13,8.790299e+10,"[AUD, BRL, CAD, CLP, USD, ZAR]",8.320930e+13,41463.0,5.108325e+13,6.073599e+13,"[AR, AU, BR, CA, CL, PE, US]","['BHP Billiton Brasil Ltda', 'Vicuña Corp.']","['Caterpillar', 'Komatsu', 'Lundin Mining', 'R...","['copper', 'energy coal', 'gold', 'iron ore', ...",98 per cent of borrowings exposed to floating ...,USD bonds issued by BHP Billiton Finance (USA)...,"['2030-12-31', '2032-12-31', '2035-12-31']",US$850 million 5-year unsecured syndicated ter...,Obligations under the Brazil Agreement (Obliga...,"Growth pipeline includes Jansen Stage 1 & 2, V...",NaN,NaN,"['BlackRock Group', 'Citigroup Global Markets ...",BHP announced a silver streaming agreement wit...,8.079944e+14,"Australia: US$2,545M; Europe: US$1,121M; China...",NaN,"All interest bearing liabilities, excluding le...",Moody's A1 (stable) / P-1; Fitch A (stable) / F1,BHP Brasil's expected payments up to FY28 for ...,4.270759e+13,NaN,Interest rate swaps and cross currency interes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.58547,2025-12-31
4,4,Bid Corporation,2025-12-31,ZAR,units,Investor presentation For the half year ended ...,1.262889e+11,1.779181e+14,1.824710e+10,2.360850e+10,2.925070e+13,9.022300e+09,8.800000e+09,1.679500e+10,2.953800e+09,1.384120e+10,"Within 1 year: R3,501,563 thousand; 1 year to ...",2.953800e+09,2.640000e+13,5.833000e+08,2.700000e+09,"[GBP, ZAR]",2.820000e+10,30581.0,2.000000e+09,1.600000e+09,"[AE, AR, AU, BH, BR, CH, CL, CN, CZ, EE, ES, H...","['Blancaluna Group', 'Broekhuyzen Horecaservic...",['Subway'],NaN,Mixture of fixed (95% fixed long-term funding)...,NaN,NaN,"A €75 million bilateral bank loan, which matur...",Capital expenditure approved and contracted fo...,NaN,NaN,NaN,"['BlackRock Advisors LLC', 'Coronation Asset M...",Group has R20.6 billion of available headroom ...,2.261642e+14,"Australasia: R23,3 bn, United Kingdom: R36,4 b...",NaN,"Property, plant and equipment with an estimate...",NaN,Liabilities matched to underlying assets for a...,NaN,NaN,NaN,5.413352e+12,NaN,NaN,36.0,62.0,36.0,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-31
5,5,Clicks Group,2026-02-28,ZAR,units,Interim group results for the six months ended...,2.487200e+10,1.904773e+13,9.034000e+09,4.100643e+12,1.192066e+13,1.238000e+09,1.900000e+09,4.414007e+12,1.334000e+09,2.708000e+09,NaN,1.334000e+09,2.600000e+09,2.073550e+11,3.110000e+08,[ZAR],2.732000e+09,20682.0,1.515000e+09,6.510000e+08,"[BW, ZA]","['Botswana', 'Eswatini', 'Lesotho', 'Namibia']","['Clicks', 'Independent pharmacies', 'Private ...",NaN,NaN,NaN,NaN,South African financial institutions provide f...,Capital commitments contracted for but not yet...,NaN,31821.000000,NaN,"['BlackRock (US and UK)', 'GIC Asset Managemen...",Diluted HEPS up 8.1% to 652.8 cps; interim div...,NaN,NaN,NaN,NaN,NaN,The group continues to hedge direct exposures ...,NaN,NaN,NaN,NaN,NaN,NaN,38.0,84.0,89.0,With 8.2% of products sourced through direct i...,7.441373e+13,NaN,NaN,NaN,ZAR,1.0,2026-02-28
6,6,Glencore,2026-06-30,ZAR,units,2026 Half-Year Results,2.864024e+15,2.755131e+15,6.268572e+14,3.866752e+13,9.071680e+13,5.953649e+13,1.329966e+11,6.961796e+11,2.967301e+14,4.463431e+14,Bond maturities maintained around a cap of no ...,2.967301e+14,2.298706e+11,2.760089e+13,6.567732e+10,"[AUD, CAD, CLP, COP, KZT, PEN, USD, ZAR]",1.167414e+14,140000.0,1.633723e+13,1.039344e+13,"[AR, AU, CA, CD, CH, GB, PE]","['Altyntau Kokshetau JSC', 'ARM Coal (Propriet...",NaN,"['coal', 'cobalt', 'copper', 'gold', 'lead', '...",Exposed to floating rate debt based primarily ...,"5-year $650 million, 4.900% coupon bond; 7-yea...","['2026-03-26', '2026-04', '2026-10', '2027-03'...","$10,635 million one-year revolving credit faci...",Contractually committed capital expenditure of...,Progressing copper projects including El Pachó...,NaN,NaN,"['BlackRock, Inc.', 'Ivan Glasenberg', 'Qatar ...",Glencore is applying to establish a secondary ...,NaN,"The Americas: $39,193 million, Europe: $66,843...",NaN,Inventories pledged under dedicated financing ...,"A3, BBB+",Uses cross-currency swaps and forward exchange...,NaN,"Uses futures, options, swaps, and physical for...",Interest rate swaps used as fair value hedges ...,NaN,NaN,9.638147e+12,NaN,NaN,NaN,NaN,1.412062e+12,NaN,NaN,NaN,USD,16.419331,2026-06-29
7,7,Gold Fields,2025-12-31,ZAR,units,Gold Fields FY 2025 Results Presentation,1.451444e+11,6.104780e+10,1.917280e+10,6.314089e+09,3.731731e+09,2.950887e+10,7.519852e+10,2.321966e+10,2.963824e+09,4.245051e+10,Borrowings comprise current portion of borrowi...,2.963824e+09,2.157272e+10,2.001866e+09,2.320307e+10,[USD],1.006738e+10,6628.0,1.263647e+10,1.309755e+10,"[AU, CA, CL, GH, PE, ZA]","['Abosso Goldfields Limited', 'Gold Fields Gha...",['Engineers and Planners (E&P)'],"['copper', 'gold']",Borrowings include variable-rate obligations (...,US$500m 10-year notes maturing in May 2029; US...,"['2029-05-31', '2032-05-31']",US$1.2bn sustainability-linked syndicated revo...,Total capital expenditure is expected to range...,"Windfall project in Canada, Salares Norte expa...",730.589962,NaN,['Public Investment Corporation (Government Em...,FY 2025 results presentation highlighting 2.44...,1.451444e+11,"Revenue generated from South Africa, Ghana, Pe...",NaN,NaN,"Moody's: Baa3, stable outlook; S&P: BBB-, stab...","Given the volatility of the gold price, Gold F...",NaN,NaN,NaN,NaN,NaN,3.821292e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.58547,2025-12-31
8,8,MTN Group,2025-12-31,ZAR,units,Mobile Telephone Networks Holdings Limited Ann...,2.273540e+11,NaN,1.310000e+09,1.856600e+10,2.147500e+10,4.190900e+10,7.751900e+10,7.045500e+10,1.775500e+10,5.270000e+10,Borrowings mature across various dates ranging...,1.775500e+10,3.594800e+10,1.989000e+10,5.082600e+10,"[BWP, CAD, CHF, CNY, EUR, GBP, GHS, KES, MUR, ...",1.473600e+10,14970.0,6.800000e+09,1.205300e+10,"[AF, BJ, BW, CD, CF, CG, CI, CM, EG, ET, GH, G...","['Bayobab', 'MTN Cameroon', 'MTN Congo-Brazzav...",NaN,NaN,Exposed to floating and fixed interest rates a...,"USD senior unsecured notes, listed and unliste...",['2026-06-30'],Various committed and uncommitted debt facilit...,"Property, plant and equipment capital commitme...",NaN,NaN,NaN,['MTN Group Limited'],The Group operates in multiple hyperinflationa...,NaN,"South Africa: R51 090m, Nigeria: R61 694m, SEA...",NaN,Certain borrowings are secured by floating cha...,NaN,"Natural hedges are considered, and derivative ...",1.812000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000e+11,NaN,NaN,NaN,ZAR,1.0,2025-12-31
9,9,NEPI Rockcastle,2025-12-31,ZAR,units,NEPI Rockcastle February 2026 Presentation,1.813585e+13,NaN,0.000000e+00,1.895970e+12,3.493808e+12,6.118924e+09,1.115794e+13,5.874713e+13,9.766485e+12,6.710200e+13,"Repayment profile: <1 year: €300,991 thousand;...",5.865418e+12,1.442040e+10,2.025929e+12,4.021790e+12,[EUR],2.772029e+11,680.0,7.622134e+12,6.566736e+11,"[BG, CZ, HR, HU, LT, PL, RO, SK]","['NE Property B.V.', 'Nepiom Limited']","['Auchan', 'Carrefour', 'CCC', 'H&M', 'LPP', '...",NaN,16% of total outstanding debt is unhedged (mai...,€500m 8-year maturity Green bond issued at 3.8...,"['2026-10-09', '2027-07-14', '2030-01-21', '20...","RCF capacity of €740m (fully undrawn, extended...",Pipeline of developments and energy projects u...,€845m total investments under permitting & con...,NaN,15.00,"['Coronation Fund Managers', 'Fortress Real Es...",Leading commercial real estate company in CEE ...,NaN,NaN,NaN,"General security over properties, current asse...",BBB/+,NaN,NaN,NaN,Interest rate caps and fixed interest rate swa...,9.870955e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUR,19.48702,2025-12-31
10,10,Naspers,2026-03-31,ZAR,units,Prosus FY26 Results Presentation,1.864866e+14,1.036094e+14,5.965232e+12,1.045205e+13,2.011332e+13,1.172417e+14,2.796955e+13,3.090059e+14,3.415826e+13,2.748476e+14,"Total long-term liabilities of US$15,988m and ...",3.415826e+13,NaN,1.177575e+13,3.764801e+12,[USD],4.617468e+13,45780.0,9.076780e+12,4.332099e+12,"[BR, CN, IN, ZA]","['Despegar', 'iFood', 'Just Eat Takeaway.com',...",NaN,NaN,NaN,Group's euro-denominated bonds and additional ...,NaN,NaN,NaN,NaN,NaN,NaN,"['Keeromstraat 30 Beleggings (RF) Limited', 'N...",Naspers holds 43% of Prosus and repurchased $1...,NaN,NaN,NaN,NaN,Investment-grade rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,17.19087,2026-03-30
11,11,OUTsurance Group,2025-12-31,ZAR,units,"RESULTS ANNOUNCEMENT, CASH ORDINARY AND SPECIA...",2.048500e+10,NaN,NaN,NaN,NaN,1.865000e+09,6.195000e+09,0.000000e+00,NaN,NaN,NaN,NaN,1.350000e+09,9.000000e+07,3.730000e+08,"[AUD, ZAR]",6.771000e+09,8100.0,3.714000e+09,2.315000e+09,"[AU, IE, ZA]","['OUTsurance Holdings Limited', 'OUTsurance Ir...",NaN,NaN,Exposed to interest rate risk through interest...,NaN,NaN,"Access to a revolving credit facility of R1,35...",Committed capital to fund growth in OUTsurance...,NaN,78.850000,NaN,"['Public Investment Corporation', 'Remgro Limi...",Multinational insurance group servicing 3.7 mi...,NaN,NaN,NaN,NaN,NaN,Utilises derivative financial instruments such...,NaN,NaN,Interest rate swaps used to manage interest ra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.211950e+11,NaN,NaN,NaN,ZAR,1.0,2025-12-31
12,12,Pepkor Holdings,2025-09-30,ZAR,units,Pepkor Holdings Limited Annual Financial State...,9.534000e+10,5.738800e+10,1.861800e+10,1.551000e+09,1.202300e+10,5.066000e+09,4.466000e+09,1.338300e+10,1.200000e+09,1.218300e+10,"Repayable next year: R1,200 million; within tw...",1.200000e+09,NaN,3.354000e+09,2.404000e+09,"[BRL, CNY, EUR, GBP, USD, ZAR]",1.068900e+10,48500.0,1.787000e+09,1.860000e+09,"[AO, BR, BW, LS, MW, MZ, NA, SZ, ZA, ZM]","['Pepco Poland Sp. z.o.o', 'Pepkor Europe GmbH...",NaN,NaN,"Borrowings bear interest at variable, market-d...",Domestic Medium Term Note Programme,"['2026-03-06', '2026-05-05', '2027-03-06', '20...",Revolving credit facilities with lenders inclu...,Contracts for capital expenditure amounting to...,NaN,2431.000000,NaN,"['Alexander Forbes Investments', 'Government o...",Ainsley Holdings Proprietary Limited and SAHPL...,1.388400e+10,"South Africa: R81,456 million, Other foreign c...",NaN,Long- and short-term investments at banking in...,NaN,Hedge between 60% and 80% of forecast US dolla...,NaN,NaN,NaN,1.190000e+09,NaN,NaN,NaN,NaN,NaN,NaN,8.980000e+07,NaN,NaN,NaN,ZAR,1.0,2025-09-30
13,13,Prosus,2026-03-31,ZAR,units,Annual Report 2026,1.668374e+11,8.935814e+10,4.658726e+09,9.798796e+09,1.906468e+10,1.148694e+11,2.766011e+10,3.002385e+11,3.352220e+10,2.667164e+11,Repayment terms of long-term liabilities: Paya...,3.271423e+10,4.297718e+10,1.108811e+10,1.012714e+11,"[BRL, CAD, EUR, GBP, INR, PLN, RON, USD, ZAR]",4.222078e+10,41998.0,8.732962e+09,4.332099e+09,"[AR, AT, AU, BR, CA, CH, CL, CO, DE, ES, FR, G...","['Dante International S.A. (eMAG)', 'Despegar....",NaN,NaN,Exposed to overnight risk-free average rates (...,Publicly traded bonds listed on the Irish Stoc...,"['2026-07-01', '2027-01-01', '2027-07-01', '20...",Undrawn multi-currency revolving credit facili...,Other service commitments of US$550m and lease...,NaN,NaN,NaN,['Naspers Limited'],Prosus has transformed from a financial holdin...,NaN,"Asia: US$808m, Europe: US$5,768m, LatAm: US$2,...",NaN,"Property, plant and equipment, investments, ca...",Baa2 (Moody's) / BBB (Standard and Poor's),NaN,NaN,NaN,NaN,1.516235e+10,NaN,1.100216e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,17.19087,2026-03-30
14,14,Sanlam,2025-12-31,ZAR,units,Sanlam Limited Annual Financial Statements 2025,2.574900e+10,1.507000e+09,NaN,1.862900e+10,3.689100e+10,3.617900e+10,2.428000e+09,1.857800e+10,3.237000e+09,1.533100e+10,"Due within one year: R6,386 million; Due withi...",6.386000e+09,3.850000e+09,1.809000e+09,4.840000e+08,"[BWP, EGP, EUR, GBP, INR, MAD, MYR, USD]",1.966700e+10,23363.0,1.117100e+10,8.085000e+09,"[CI, GH, KE, MY, NA, ZA]","['MCIS Insurance', 'Pacific & Orient Insurance...",NaN,NaN,Exposed to fixed-rate and floating-rate intere...,Unsecured subordinated bonds and commercial pa...,"['2026-08-16', '2028-04-06', '2028-08-16', '20...",Standard Bank bridge loan facility of R6.5 bil...,Future lease commitments amounting to R165 mil...,NaN,NaN,NaN,"['Government Employees Pension Fund (PIC)', 'U...",Sanlam announced various subsequent strategic ...,NaN,"South Africa: R23,618 million; Pan-Africa: R25...",NaN,"Repurchase agreement positions of R17,961 mill...",South Africa National Scale: zaA+ for Sanlam L...,Foreign currency mismatch risk is mitigated by...,NaN,NaN,"Interest rate swaps, caps, floors and other de...",1.590000e+09,NaN,1.280000e+08,NaN,NaN,NaN,NaN,NaN,1.348527e+12,NaN,NaN,ZAR,1.0,2025-12-31
15,15,Shaftesbury Capital plc,2025-12-31,ZAR,units,2025 Annual Report,5.334637e+09,6.341720e+08,NaN,4.064060e+08,NaN,8.070062e+09,2.599212e+09,2.703716e+10,9.789472e+09,1.724769e+10,Debt matures between March 2026 and 2037. 2026...,9.789472e+09,1.507275e+10,1.424654e+09,2.559018e+09,[GBP],6.341720e+08,101.0,1.612226e+09,NaN,[GB],NaN,"['CBRE', 'Cushman & Wakefield', 'Veolia']",NaN,Majority of debt is at fixed rates or has inte...,£275 million of secured exchangeable bonds mat...,['2026-03-31'],Three revolving credit facilities totalling £7...,Contractually committed to £10.8 million of fu...,NaN,32.378500,26.10,"['BlackRock, Inc.', 'Government of South Afric...",Shaftesbury Capital is a central London mixed-...,NaN,All revenue has been generated from operations...,NaN,£517.4 million of borrowings are secured by fi...,NaN,NaN,NaN,NaN,Interest rate caps protecting against SONIA ex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.157699e+11,NaN,NaN,GBP,22.33,2025-12-31
16,16,Shoprite Holdings,2025-12-28,ZAR,units,2026 Interim Results Presentation,1.367960e+11,1.041790e+11,3.370000e+10,3.506000e+09,2.447400e+10,1.510000e+10,1.098400e+10,6.993000e+09,4.890000e+08,6.504000e+09,Borrowings consist of short-term and long-term...,4.890000e+08,1.160000e+10,2.525000e+09,3.931000e+09,[ZAR],1.080100e+10,168939.0,2.700000e+09,3.366000e+09,"[BW, GH, LS, MW, MZ, NA, SZ, ZA, ZM]","['Africa Supermarkets Ltd', 'Checkers (Chatswo...",NaN,NaN,Borrowings and call accounts carry floating in...,NaN,NaN,Unutilised banking facilities of R11.6 billion...,"Contracted for property, plant and equipment a...",NaN,NaN,NaN,"['BlackRock', 'Capital Group', 'CH Wiese', 'Co...",Group plans to add 123 new stores within core ...,2.304400e+10,"South Africa: R229,657 million (external sale ...",NaN,Borrowings and credit facilities are unsecured.,NaN,The Group uses call deposits in foreign curren...,2.125000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-28

In [ ]:
new_company_lvl_df, new_sens_df = my_processor.validate_external_data(standard_ext_data, standard_sens_data)
#TODO Fix units

16:46:29 | WARNING | Anglo American: original_currency differs from yfinance AGL.JO ('AUD' != 'USD'); using the yfinance value
16:46:33 | WARNING | AngloGold Ashanti: original_currency differs from yfinance ANG.JO ('CAD' != 'USD'); using the yfinance value
16:46:36 | WARNING | Aspen Pharmacare: original_currency differs from yfinance APN.JO ('AUD' != 'ZAR'); using the yfinance value
16:46:40 | WARNING | BHP Group: original_currency differs from yfinance BHG.JO ('EUR' != 'USD'); using the yfinance value
16:46:43 | WARNING | Bid Corporation: original_currency differs from yfinance BID.JO ('EUR' != 'ZAR'); using the yfinance value
16:46:43 | WARNING | Bid Corporation: original_currency differs from yfinance BID.JO ('EUR' != 'ZAR'); using the yfinance value
16:46:51 | WARNING | Gold Fields: original_currency differs from yfinance GFI.JO ('AUD' != 'USD'); using the yfinance value
16:46:51 | WARNING | Gold Fields: original_currency differs from yfinance GFI.JO ('AUD' != 'USD'); using the yfinance value
16:46:51 | WARNING | Gold Fields: original_currency differs from yfinance GFI.JO ('ZAR' != 'USD'); using the yfinance value
16:46:51 | WARNING | Gold Fields: original_currency differs from yfinance GFI.JO ('AUD' != 'USD'); using the yfinance value
16:46:51 | WARNING | Gold Fields: original_currency differs from yfinance GFI.JO ('ZAR' != 'USD'); using the yfinance value
16:46:54 | WARNING | MTN Group: original_currency differs from yfinance MTN.JO ('USD' != 'ZAR'); using the yfinance value
16:47:02 | WARNING | Naspers: original_currency differs from yfinance NPN.JO ('EUR' != 'USD'); using the yfinance value
16:47:02 | WARNING | Naspers: original_currency differs from yfinance NPN.JO ('EUR' != 'USD'); using the yfinance value
16:47:02 | WARNING | Naspers: original_currency differs from yfinance NPN.JO ('EUR' != 'USD'); using the yfinance value
16:47:02 | WARNING | Naspers: original_currency differs from yfinance NPN.JO ('EUR' != 'USD'); using the yfinance value
16:47:22 | WARNING | Prosus: original_currency differs from yfinance PRX.JO ('EUR' != 'USD'); using the yfinance value
16:47:22 | WARNING | Prosus: original_currency differs from yfinance PRX.JO ('EUR' != 'USD'); using the yfinance value
16:47:22 | WARNING | Prosus: original_currency differs from yfinance PRX.JO ('EUR' != 'USD'); using the yfinance value
16:47:22 | WARNING | Prosus: original_currency differs from yfinance PRX.JO ('EUR' != 'USD'); using the yfinance value
16:47:22 | WARNING | Prosus: original_currency differs from yfinance PRX.JO ('EUR' != 'USD'); using the yfinance value
16:47:25 | WARNING | Sanlam: original_currency differs from yfinance SLM.JO ('GBP' != 'ZAR'); using the yfinance value
16:47:25 | WARNING | Sanlam: original_currency differs from yfinance SLM.JO ('USD' != 'ZAR'); using the yfinance value
16:47:35 | WARNING | The Bidvest Group: original_currency differs from yfinance BVT.JO ('USD' != 'ZAR'); using the yfinance value
16:47:35 | WARNING | The Bidvest Group: original_currency differs from yfinance BVT.JO ('USD' != 'ZAR'); using the yfinance value
16:47:42 | WARNING | Vodacom Group: original_currency differs from yfinance VOD.JO ('USD' != 'ZAR'); using the yfinance value

In [ ]:
new_company_lvl_df

,Unnamed: 0,company,report_date,reporting_currency,reporting_unit,source_document,revenue,cost_of_sales,inventory,trade_receivables,trade_payables,cash_and_cash_equivalents,operating_cash_flow,total_debt,short_term_debt,long_term_debt,debt_maturity_schedule,debt_due_within_12_months,undrawn_committed_facilities,finance_costs,capital_expenditure,currencies_exposed_to,employee_expenses,employee_count,dividends_paid,tax_paid,countries_of_operation,foreign_subsidiaries,major_customers_suppliers,commodity_exposure,interest_rate_exposure,bond_issues,bond_maturity_dates,credit_facilities_and_lenders,major_contractual_commitments,order_book_project_pipeline,share_price,share_return,ownership_major_shareholders,extra_notes,foreign_revenue,revenue_by_geography,exports_exposure,security_collateral_on_debt,credit_rating,fx_hedging_policy,contingent_liabilities,commodity_derivatives,interest_rate_derivatives,debt_due_12_to_24_months,fx_derivative_notional,guarantees_outstanding,receivable_days,payable_days,inventory_days,imports_exposure,market_capitalisation,assets_under_management,foreign_currency_assets,foreign_currency_liabilities,original_currency,fx_rate_to_zar,fx_rate_date
0,0,Anglo American,2026-06-30,ZAR,units,Our 2026 Half Year Results,3.045129e+14,2.823140e+14,6.270542e+13,3.924220e+13,4.070352e+13,1.056748e+14,1.150174e+14,1.346385e+11,1.765078e+13,2.365369e+14,"Medium and long-term borrowings of $14,406 mil...",1.765078e+13,9.771144e+13,8.078311e+12,5.454502e+13,[USD],5.454502e+13,43000.0,5.648250e+12,2.182129e+13,"[AU, BR, BW, CA, CL, CO, DE, EC, FI, GB, NA, P...","['Anglo American Quellaveco S.A.', 'Anglo Amer...","['China customers', 'Enel X', 'Mitsubishi Corp...","['copper', 'crop nutrients', 'iron ore', 'mang...",Principally exposed to US and South African in...,EUR 745 million sustainability-linked notes du...,"['2026-03', '2027-04', '2027-05', '2027-09', '...",Bilateral and syndicated borrowing facilities ...,Capital commitments relating to acquisition of...,Joint mine plan agreed with Codelco to unlock ...,NaN,NaN,"['BlackRock Inc.', 'Epoch Two Investment Holdi...",Anglo American is progressing a portfolio tran...,NaN,"China $9,612m, Other Asia $3,239m, Other Afric...","Global sales across Asia, Europe, South Americ...",NaN,NaN,"Generally not to hedge South African rand, Aus...",4.778025e+12,"Interest rate swaps, cross-currency interest r...",Interest rate swaps used to convert fixed rate...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.419331,2026-06-29
1,1,AngloGold Ashanti,2026-06-30,ZAR,units,Q2 2026 Earnings Results,5.096560e+10,2.508874e+10,2.109884e+10,2.003158e+09,9.161986e+09,4.546513e+10,1.993307e+10,2.919357e+10,1.970320e+08,2.559774e+10,"Total borrowings of $2,044 million. $19 millio...",1.970320e+08,2.405432e+10,6.239346e+08,9.014212e+09,[USD],1.444901e+10,41416.0,1.357879e+10,8.899277e+09,"[AR, AU, BR, CD, CO, EG, GH, GN, TZ, US]","['AngloGold Ashanti (Ghana) Limited', 'AngloGo...","['ANZ Investment Bank Ltd', 'JP Morgan Chase N...",['gold'],Exposed to variable interest rates on borrowin...,Repurchased approximately $666m principal amou...,"['2028-11-01', '2030-10-01', '2040-04-15']",Undrawn $1.4bn multi-currency revolving credit...,Contracted capital expenditure of $378 million...,Advanced exploration and development projects ...,1400.240513,2.75,"['BlackRock, Inc.', 'Public Investment Corpora...",Q2 2026 earnings results presentation; targeti...,1.624364e+11,"Africa: $7,152m, Australia: $1,876m, Americas:...",Refined gold and doré bars sold directly to bu...,"Unsecured borrowings and credit facilities, wi...",BB+ / Baa3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.419331,2026-06-29
2,2,Aspen Pharmacare,2025-12-31,ZAR,units,Interim Results Presentation H1 2026,2.108500e+10,1.150100e+10,1.691900e+10,1.116600e+10,4.084000e+09,6.642000e+09,3.577000e+09,2.856700e+10,4.612000e+09,3.150800e+10,"Less than 1 year: R4,612 million; Between 1-2 ...",4.612000e+09,1.590000e+10,7.250000e+08,1.580000e+09,"[AUD, BRL, CNY, EUR, MXN, USD, ZAR]",1.087400e+10,9557.0,9.410000e+08,2.640000e+08,"[CN, ZA]","['A.Pharma Distribuidora Limitada', 'Alphamed ...",NaN,NaN,Exposed to floating and fixed interest rates a...,NaN,NaN,Euro syndicated term and revolving loans (Faci...,Authorised and contracted capital commitments ...,NaN,NaN,NaN,"['Allan Gray', 'Attridge, MG', 'Bank of New Yo...",Interim results for the period ended 31 Decemb...,NaN,"Africa Middle East: R10,086 million; Americas:...",NaN,Inventories to the value of R3.5 billion have ...,BB or better international credit rating,Through the selective use of forward exchange ...,2.790000e+08,NaN,NaN,3.741000e+09,5.022000e+09,7.317500e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-31
3,3,BHP Group,2025-12-31,ZAR,units,Financial results for the half year ended 31 D...,4.627678e+11,NaN,9.647768e+13,9.042398e+13,1.042894e+14,2.233399e+14,1.554390e+14,4.647415e+14,5.690475e+13,4.078367e+14,"Bank loans, debentures and other loans undisco...",5.690475e+13,9.122009e+13,1.169276e+13,8.790299e+10,"[AUD, BRL, CAD, CLP, USD, ZAR]",8.320930e+13,41463.0,5.108325e+13,6.073599e+13,"[AR, AU, BR, CA, CL, PE, US]","['BHP Billiton Brasil Ltda', 'Vicuña Corp.']","['Caterpillar', 'Komatsu', 'Lundin Mining', 'R...","['copper', 'energy coal', 'gold', 'iron ore', ...",98 per cent of borrowings exposed to floating ...,USD bonds issued by BHP Billiton Finance (USA)...,"['2030-12-31', '2032-12-31', '2035-12-31']",US$850 million 5-year unsecured syndicated ter...,Obligations under the Brazil Agreement (Obliga...,"Growth pipeline includes Jansen Stage 1 & 2, V...",NaN,NaN,"['BlackRock Group', 'Citigroup Global Markets ...",BHP announced a silver streaming agreement wit...,8.079944e+14,"Australia: US$2,545M; Europe: US$1,121M; China...",NaN,"All interest bearing liabilities, excluding le...",Moody's A1 (stable) / P-1; Fitch A (stable) / F1,BHP Brasil's expected payments up to FY28 for ...,4.270759e+13,NaN,Interest rate swaps and cross currency interes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.58547,2025-12-31
4,4,Bid Corporation,2025-12-31,ZAR,units,Investor presentation For the half year ended ...,1.262889e+11,1.779181e+14,1.824710e+10,2.360850e+10,2.925070e+13,9.022300e+09,8.800000e+09,1.679500e+10,2.953800e+09,1.384120e+10,"Within 1 year: R3,501,563 thousand; 1 year to ...",2.953800e+09,2.640000e+13,5.833000e+08,2.700000e+09,"[GBP, ZAR]",2.820000e+10,30581.0,2.000000e+09,1.600000e+09,"[AE, AR, AU, BH, BR, CH, CL, CN, CZ, EE, ES, H...","['Blancaluna Group', 'Broekhuyzen Horecaservic...",['Subway'],NaN,Mixture of fixed (95% fixed long-term funding)...,NaN,NaN,"A €75 million bilateral bank loan, which matur...",Capital expenditure approved and contracted fo...,NaN,NaN,NaN,"['BlackRock Advisors LLC', 'Coronation Asset M...",Group has R20.6 billion of available headroom ...,2.261642e+14,"Australasia: R23,3 bn, United Kingdom: R36,4 b...",NaN,"Property, plant and equipment with an estimate...",NaN,Liabilities matched to underlying assets for a...,NaN,NaN,NaN,5.413352e+12,NaN,NaN,36.0,62.0,36.0,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-31
5,5,Clicks Group,2026-02-28,ZAR,units,Interim group results for the six months ended...,2.487200e+10,1.904773e+13,9.034000e+09,4.100643e+12,1.192066e+13,1.238000e+09,1.900000e+09,4.414007e+12,1.334000e+09,2.708000e+09,NaN,1.334000e+09,2.600000e+09,2.073550e+11,3.110000e+08,[ZAR],2.732000e+09,20682.0,1.515000e+09,6.510000e+08,"[BW, ZA]","['Botswana', 'Eswatini', 'Lesotho', 'Namibia']","['Clicks', 'Independent pharmacies', 'Private ...",NaN,NaN,NaN,NaN,South African financial institutions provide f...,Capital commitments contracted for but not yet...,NaN,31821.000000,NaN,"['BlackRock (US and UK)', 'GIC Asset Managemen...",Diluted HEPS up 8.1% to 652.8 cps; interim div...,NaN,NaN,NaN,NaN,NaN,The group continues to hedge direct exposures ...,NaN,NaN,NaN,NaN,NaN,NaN,38.0,84.0,89.0,With 8.2% of products sourced through direct i...,7.441373e+13,NaN,NaN,NaN,ZAR,1.0,2026-02-28
6,6,Glencore,2026-06-30,ZAR,units,2026 Half-Year Results,2.864024e+15,2.755131e+15,6.268572e+14,3.866752e+13,9.071680e+13,5.953649e+13,1.329966e+11,6.961796e+11,2.967301e+14,4.463431e+14,Bond maturities maintained around a cap of no ...,2.967301e+14,2.298706e+11,2.760089e+13,6.567732e+10,"[AUD, CAD, CLP, COP, KZT, PEN, USD, ZAR]",1.167414e+14,140000.0,1.633723e+13,1.039344e+13,"[AR, AU, CA, CD, CH, GB, PE]","['Altyntau Kokshetau JSC', 'ARM Coal (Propriet...",NaN,"['coal', 'cobalt', 'copper', 'gold', 'lead', '...",Exposed to floating rate debt based primarily ...,"5-year $650 million, 4.900% coupon bond; 7-yea...","['2026-03-26', '2026-04', '2026-10', '2027-03'...","$10,635 million one-year revolving credit faci...",Contractually committed capital expenditure of...,Progressing copper projects including El Pachó...,NaN,NaN,"['BlackRock, Inc.', 'Ivan Glasenberg', 'Qatar ...",Glencore is applying to establish a secondary ...,NaN,"The Americas: $39,193 million, Europe: $66,843...",NaN,Inventories pledged under dedicated financing ...,"A3, BBB+",Uses cross-currency swaps and forward exchange...,NaN,"Uses futures, options, swaps, and physical for...",Interest rate swaps used as fair value hedges ...,NaN,NaN,9.638147e+12,NaN,NaN,NaN,NaN,1.412062e+12,NaN,NaN,NaN,USD,16.419331,2026-06-29
7,7,Gold Fields,2025-12-31,ZAR,units,Gold Fields FY 2025 Results Presentation,1.451444e+11,6.104780e+10,1.917280e+10,6.314089e+09,3.731731e+09,2.950887e+10,7.519852e+10,2.321966e+10,2.963824e+09,4.245051e+10,Borrowings comprise current portion of borrowi...,2.963824e+09,2.157272e+10,2.001866e+09,2.320307e+10,[USD],1.006738e+10,6628.0,1.263647e+10,1.309755e+10,"[AU, CA, CL, GH, PE, ZA]","['Abosso Goldfields Limited', 'Gold Fields Gha...",['Engineers and Planners (E&P)'],"['copper', 'gold']",Borrowings include variable-rate obligations (...,US$500m 10-year notes maturing in May 2029; US...,"['2029-05-31', '2032-05-31']",US$1.2bn sustainability-linked syndicated revo...,Total capital expenditure is expected to range...,"Windfall project in Canada, Salares Norte expa...",730.589962,NaN,['Public Investment Corporation (Government Em...,FY 2025 results presentation highlighting 2.44...,1.451444e+11,"Revenue generated from South Africa, Ghana, Pe...",NaN,NaN,"Moody's: Baa3, stable outlook; S&P: BBB-, stab...","Given the volatility of the gold price, Gold F...",NaN,NaN,NaN,NaN,NaN,3.821292e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,16.58547,2025-12-31
8,8,MTN Group,2025-12-31,ZAR,units,Mobile Telephone Networks Holdings Limited Ann...,2.273540e+11,NaN,1.310000e+09,1.856600e+10,2.147500e+10,4.190900e+10,7.751900e+10,7.045500e+10,1.775500e+10,5.270000e+10,Borrowings mature across various dates ranging...,1.775500e+10,3.594800e+10,1.989000e+10,5.082600e+10,"[BWP, CAD, CHF, CNY, EUR, GBP, GHS, KES, MUR, ...",1.473600e+10,14970.0,6.800000e+09,1.205300e+10,"[AF, BJ, BW, CD, CF, CG, CI, CM, EG, ET, GH, G...","['Bayobab', 'MTN Cameroon', 'MTN Congo-Brazzav...",NaN,NaN,Exposed to floating and fixed interest rates a...,"USD senior unsecured notes, listed and unliste...",['2026-06-30'],Various committed and uncommitted debt facilit...,"Property, plant and equipment capital commitme...",NaN,NaN,NaN,['MTN Group Limited'],The Group operates in multiple hyperinflationa...,NaN,"South Africa: R51 090m, Nigeria: R61 694m, SEA...",NaN,Certain borrowings are secured by floating cha...,NaN,"Natural hedges are considered, and derivative ...",1.812000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000e+11,NaN,NaN,NaN,ZAR,1.0,2025-12-31
9,9,NEPI Rockcastle,2025-12-31,ZAR,units,NEPI Rockcastle February 2026 Presentation,1.813585e+13,NaN,0.000000e+00,1.895970e+12,3.493808e+12,6.118924e+09,1.115794e+13,5.874713e+13,9.766485e+12,6.710200e+13,"Repayment profile: <1 year: €300,991 thousand;...",5.865418e+12,1.442040e+10,2.025929e+12,4.021790e+12,[EUR],2.772029e+11,680.0,7.622134e+12,6.566736e+11,"[BG, CZ, HR, HU, LT, PL, RO, SK]","['NE Property B.V.', 'Nepiom Limited']","['Auchan', 'Carrefour', 'CCC', 'H&M', 'LPP', '...",NaN,16% of total outstanding debt is unhedged (mai...,€500m 8-year maturity Green bond issued at 3.8...,"['2026-10-09', '2027-07-14', '2030-01-21', '20...","RCF capacity of €740m (fully undrawn, extended...",Pipeline of developments and energy projects u...,€845m total investments under permitting & con...,NaN,15.00,"['Coronation Fund Managers', 'Fortress Real Es...",Leading commercial real estate company in CEE ...,NaN,NaN,NaN,"General security over properties, current asse...",BBB/+,NaN,NaN,NaN,Interest rate caps and fixed interest rate swa...,9.870955e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUR,19.48702,2025-12-31
10,10,Naspers,2026-03-31,ZAR,units,Prosus FY26 Results Presentation,1.864866e+14,1.036094e+14,5.965232e+12,1.045205e+13,2.011332e+13,1.172417e+14,2.796955e+13,3.090059e+14,3.415826e+13,2.748476e+14,"Total long-term liabilities of US$15,988m and ...",3.415826e+13,NaN,1.177575e+13,3.764801e+12,[USD],4.617468e+13,45780.0,9.076780e+12,4.332099e+12,"[BR, CN, IN, ZA]","['Despegar', 'iFood', 'Just Eat Takeaway.com',...",NaN,NaN,NaN,Group's euro-denominated bonds and additional ...,NaN,NaN,NaN,NaN,NaN,NaN,"['Keeromstraat 30 Beleggings (RF) Limited', 'N...",Naspers holds 43% of Prosus and repurchased $1...,NaN,NaN,NaN,NaN,Investment-grade rating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,17.19087,2026-03-30
11,11,OUTsurance Group,2025-12-31,ZAR,units,"RESULTS ANNOUNCEMENT, CASH ORDINARY AND SPECIA...",2.048500e+10,NaN,NaN,NaN,NaN,1.865000e+09,6.195000e+09,0.000000e+00,NaN,NaN,NaN,NaN,1.350000e+09,9.000000e+07,3.730000e+08,"[AUD, ZAR]",6.771000e+09,8100.0,3.714000e+09,2.315000e+09,"[AU, IE, ZA]","['OUTsurance Holdings Limited', 'OUTsurance Ir...",NaN,NaN,Exposed to interest rate risk through interest...,NaN,NaN,"Access to a revolving credit facility of R1,35...",Committed capital to fund growth in OUTsurance...,NaN,78.850000,NaN,"['Public Investment Corporation', 'Remgro Limi...",Multinational insurance group servicing 3.7 mi...,NaN,NaN,NaN,NaN,NaN,Utilises derivative financial instruments such...,NaN,NaN,Interest rate swaps used to manage interest ra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.211950e+11,NaN,NaN,NaN,ZAR,1.0,2025-12-31
12,12,Pepkor Holdings,2025-09-30,ZAR,units,Pepkor Holdings Limited Annual Financial State...,9.534000e+10,5.738800e+10,1.861800e+10,1.551000e+09,1.202300e+10,5.066000e+09,4.466000e+09,1.338300e+10,1.200000e+09,1.218300e+10,"Repayable next year: R1,200 million; within tw...",1.200000e+09,NaN,3.354000e+09,2.404000e+09,"[BRL, CNY, EUR, GBP, USD, ZAR]",1.068900e+10,48500.0,1.787000e+09,1.860000e+09,"[AO, BR, BW, LS, MW, MZ, NA, SZ, ZA, ZM]","['Pepco Poland Sp. z.o.o', 'Pepkor Europe GmbH...",NaN,NaN,"Borrowings bear interest at variable, market-d...",Domestic Medium Term Note Programme,"['2026-03-06', '2026-05-05', '2027-03-06', '20...",Revolving credit facilities with lenders inclu...,Contracts for capital expenditure amounting to...,NaN,2431.000000,NaN,"['Alexander Forbes Investments', 'Government o...",Ainsley Holdings Proprietary Limited and SAHPL...,1.388400e+10,"South Africa: R81,456 million, Other foreign c...",NaN,Long- and short-term investments at banking in...,NaN,Hedge between 60% and 80% of forecast US dolla...,NaN,NaN,NaN,1.190000e+09,NaN,NaN,NaN,NaN,NaN,NaN,8.980000e+07,NaN,NaN,NaN,ZAR,1.0,2025-09-30
13,13,Prosus,2026-03-31,ZAR,units,Annual Report 2026,1.668374e+11,8.935814e+10,4.658726e+09,9.798796e+09,1.906468e+10,1.148694e+11,2.766011e+10,3.002385e+11,3.352220e+10,2.667164e+11,Repayment terms of long-term liabilities: Paya...,3.271423e+10,4.297718e+10,1.108811e+10,1.012714e+11,"[BRL, CAD, EUR, GBP, INR, PLN, RON, USD, ZAR]",4.222078e+10,41998.0,8.732962e+09,4.332099e+09,"[AR, AT, AU, BR, CA, CH, CL, CO, DE, ES, FR, G...","['Dante International S.A. (eMAG)', 'Despegar....",NaN,NaN,Exposed to overnight risk-free average rates (...,Publicly traded bonds listed on the Irish Stoc...,"['2026-07-01', '2027-01-01', '2027-07-01', '20...",Undrawn multi-currency revolving credit facili...,Other service commitments of US$550m and lease...,NaN,NaN,NaN,['Naspers Limited'],Prosus has transformed from a financial holdin...,NaN,"Asia: US$808m, Europe: US$5,768m, LatAm: US$2,...",NaN,"Property, plant and equipment, investments, ca...",Baa2 (Moody's) / BBB (Standard and Poor's),NaN,NaN,NaN,NaN,1.516235e+10,NaN,1.100216e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USD,17.19087,2026-03-30
14,14,Sanlam,2025-12-31,ZAR,units,Sanlam Limited Annual Financial Statements 2025,2.574900e+10,1.507000e+09,NaN,1.862900e+10,3.689100e+10,3.617900e+10,2.428000e+09,1.857800e+10,3.237000e+09,1.533100e+10,"Due within one year: R6,386 million; Due withi...",6.386000e+09,3.850000e+09,1.809000e+09,4.840000e+08,"[BWP, EGP, EUR, GBP, INR, MAD, MYR, USD]",1.966700e+10,23363.0,1.117100e+10,8.085000e+09,"[CI, GH, KE, MY, NA, ZA]","['MCIS Insurance', 'Pacific & Orient Insurance...",NaN,NaN,Exposed to fixed-rate and floating-rate intere...,Unsecured subordinated bonds and commercial pa...,"['2026-08-16', '2028-04-06', '2028-08-16', '20...",Standard Bank bridge loan facility of R6.5 bil...,Future lease commitments amounting to R165 mil...,NaN,NaN,NaN,"['Government Employees Pension Fund (PIC)', 'U...",Sanlam announced various subsequent strategic ...,NaN,"South Africa: R23,618 million; Pan-Africa: R25...",NaN,"Repurchase agreement positions of R17,961 mill...",South Africa National Scale: zaA+ for Sanlam L...,Foreign currency mismatch risk is mitigated by...,NaN,NaN,"Interest rate swaps, caps, floors and other de...",1.590000e+09,NaN,1.280000e+08,NaN,NaN,NaN,NaN,NaN,1.348527e+12,NaN,NaN,ZAR,1.0,2025-12-31
15,15,Shaftesbury Capital plc,2025-12-31,ZAR,units,2025 Annual Report,5.334637e+09,6.341720e+08,NaN,4.064060e+08,NaN,8.070062e+09,2.599212e+09,2.703716e+10,9.789472e+09,1.724769e+10,Debt matures between March 2026 and 2037. 2026...,9.789472e+09,1.507275e+10,1.424654e+09,2.559018e+09,[GBP],6.341720e+08,101.0,1.612226e+09,NaN,[GB],NaN,"['CBRE', 'Cushman & Wakefield', 'Veolia']",NaN,Majority of debt is at fixed rates or has inte...,£275 million of secured exchangeable bonds mat...,['2026-03-31'],Three revolving credit facilities totalling £7...,Contractually committed to £10.8 million of fu...,NaN,32.378500,26.10,"['BlackRock, Inc.', 'Government of South Afric...",Shaftesbury Capital is a central London mixed-...,NaN,All revenue has been generated from operations...,NaN,£517.4 million of borrowings are secured by fi...,NaN,NaN,NaN,NaN,Interest rate caps protecting against SONIA ex...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.157699e+11,NaN,NaN,GBP,22.33,2025-12-31
16,16,Shoprite Holdings,2025-12-28,ZAR,units,2026 Interim Results Presentation,1.367960e+11,1.041790e+11,3.370000e+10,3.506000e+09,2.447400e+10,1.510000e+10,1.098400e+10,6.993000e+09,4.890000e+08,6.504000e+09,Borrowings consist of short-term and long-term...,4.890000e+08,1.160000e+10,2.525000e+09,3.931000e+09,[ZAR],1.080100e+10,168939.0,2.700000e+09,3.366000e+09,"[BW, GH, LS, MW, MZ, NA, SZ, ZA, ZM]","['Africa Supermarkets Ltd', 'Checkers (Chatswo...",NaN,NaN,Borrowings and call accounts carry floating in...,NaN,NaN,Unutilised banking facilities of R11.6 billion...,"Contracted for property, plant and equipment a...",NaN,NaN,NaN,"['BlackRock', 'Capital Group', 'CH Wiese', 'Co...",Group plans to add 123 new stores within core ...,2.304400e+10,"South Africa: R229,657 million (external sale ...",NaN,Borrowings and credit facilities are unsecured.,NaN,The Group uses call deposits in foreign curren...,2.125000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZAR,1.0,2025-12-28

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
print(new_company_lvl_df[new_company_lvl_df.company == "BHP Group"])

   Unnamed: 0    company report_date reporting_currency reporting_unit  \
3           3  BHP Group  2025-12-31                ZAR          units

                                     source_document       revenue  \
3  Financial results for the half year ended 31 D...  4.627678e+11

   cost_of_sales     inventory  trade_receivables  trade_payables  \
3            NaN  9.647768e+13       9.042398e+13    1.042894e+14

   cash_and_cash_equivalents  operating_cash_flow    total_debt  \
3               2.233399e+14         1.554390e+14  4.647415e+14

   short_term_debt  long_term_debt  \
3     5.690475e+13    4.078367e+14

                              debt_maturity_schedule  \
3  Bank loans, debentures and other loans undisco...

   debt_due_within_12_months  undrawn_committed_facilities  finance_costs  \
3               5.690475e+13                  9.122009e+13   1.169276e+13

   capital_expenditure           currencies_exposed_to  employee_expenses  \
3         8.790299e+10  [AUD, BRL, CAD, CLP, USD, ZAR]       8.320930e+13

   employee_count  dividends_paid      tax_paid        countries_of_operation  \
3         41463.0    5.108325e+13  6.073599e+13  [AR, AU, BR, CA, CL, PE, US]

                           foreign_subsidiaries  \
3  ['BHP Billiton Brasil Ltda', 'Vicuña Corp.']

                           major_customers_suppliers  \
3  ['Caterpillar', 'Komatsu', 'Lundin Mining', 'R...

                                  commodity_exposure  \
3  ['copper', 'energy coal', 'gold', 'iron ore', ...

                              interest_rate_exposure  \
3  98 per cent of borrowings exposed to floating ...

                                         bond_issues  \
3  USD bonds issued by BHP Billiton Finance (USA)...

                          bond_maturity_dates  \
3  ['2030-12-31', '2032-12-31', '2035-12-31']

                       credit_facilities_and_lenders  \
3  US$850 million 5-year unsecured syndicated ter...

                       major_contractual_commitments  \
3  Obligations under the Brazil Agreement (Obliga...

                         order_book_project_pipeline  share_price  \
3  Growth pipeline includes Jansen Stage 1 & 2, V...          NaN

   share_return                       ownership_major_shareholders  \
3           NaN  ['BlackRock Group', 'Citigroup Global Markets ...

                                         extra_notes  foreign_revenue  \
3  BHP announced a silver streaming agreement wit...     8.079944e+14

                                revenue_by_geography exports_exposure  \
3  Australia: US$2,545M; Europe: US$1,121M; China...              NaN

                         security_collateral_on_debt  \
3  All interest bearing liabilities, excluding le...

                                      credit_rating  \
3  Moody's A1 (stable) / P-1; Fitch A (stable) / F1

                                   fx_hedging_policy  contingent_liabilities  \
3  BHP Brasil's expected payments up to FY28 for ...            4.270759e+13

  commodity_derivatives                          interest_rate_derivatives  \
3                   NaN  Interest rate swaps and cross currency interes...

   debt_due_12_to_24_months  fx_derivative_notional  guarantees_outstanding  \
3                       NaN                     NaN                     NaN

   receivable_days  payable_days  inventory_days imports_exposure  \
3              NaN           NaN             NaN              NaN

   market_capitalisation  assets_under_management  foreign_currency_assets  \
3                    NaN                      NaN                      NaN

   foreign_currency_liabilities original_currency fx_rate_to_zar fx_rate_date
3                           NaN               USD       16.58547   2025-12-31

In [ ]:

cross_border_payments = pd.read_csv("../data/cross_border_payments.csv")
trade_finance = pd.read_csv("../data/trade_finance.csv")
transactional_banking = pd.read_csv("../data/transactional_banking.csv")

In [ ]:
calculate_total_wallet_size(new_company_lvl_df)

,transactional_banking,global_markets,investment_banking,total,transactional_banking_confidence,global_markets_confidence,investment_banking_confidence
company,,,,,,,
Anglo American,1.061608e+15,1.346385e+11,5.467965e+13,1.116423e+15,low,low,low
AngloGold Ashanti,1.835353e+11,1.916300e+11,3.820778e+10,4.133731e+11,low,low,low
Aspen Pharmacare,1.359830e+11,3.358900e+10,3.014700e+10,1.997190e+11,low,low,low
BHP Group,2.669731e+14,1.272736e+15,4.648294e+14,2.004538e+15,low,low,low
Bid Corporation,3.560034e+14,2.261810e+14,1.949500e+10,5.822039e+14,low,low,low
Clicks Group,3.812647e+13,4.414007e+12,4.414318e+12,4.695480e+13,low,low,low
Glencore,8.586932e+15,6.961796e+11,7.618569e+11,8.588390e+15,low,low,low
Gold Fields,3.363716e+11,1.683641e+11,4.642273e+10,5.511584e+11,low,low,low
MTN Group,4.984290e+11,7.045500e+10,1.212810e+11,6.901650e+11,low,low,low
NEPI Rockcastle,3.627782e+13,5.874713e+13,6.276892e+13,1.577939e+14,low,low,low
Naspers,5.705306e+14,3.090059e+14,3.127707e+14,1.192307e+15,low,low,low
OUTsurance Group,4.283500e+10,0.000000e+00,3.730000e+08,4.320800e+10,low,low,low
Pepkor Holdings,2.295180e+11,2.726700e+10,1.578700e+10,2.725720e+11,low,low,low
Prosus,5.158189e+11,3.002385e+11,4.015100e+11,1.217567e+12,low,low,low
Sanlam,1.039930e+11,1.857800e+10,1.906200e+10,1.416330e+11,low,low,low
Shaftesbury Capital plc,1.530721e+10,2.703716e+10,2.959618e+10,7.194056e+10,low,low,low
Shoprite Holdings,3.792460e+11,3.003700e+10,1.092400e+10,4.202070e+11,low,low,low
The Bidvest Group,1.417838e+17,5.681297e+16,3.839892e+16,2.369957e+17,low,low,low
Valterra Platinum,1.188041e+14,7.806100e+13,2.006300e+12,1.988714e+14,low,low,low
Vodacom Group,2.086115e+14,8.710000e+10,1.107000e+11,2.088093e+14,low,low,low